global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'amysoft-prod'
    environment: 'production'

# Alertmanager configuration
alertmanager_config:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Admin Console monitoring
  - job_name: 'admin-console'
    static_configs:
      - targets: ['admin:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Website monitoring
  - job_name: 'website'
    static_configs:
      - targets: ['website:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  # API monitoring
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    
  # PWA monitoring
  - job_name: 'pwa'
    static_configs:
      - targets: ['pwa:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Database monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    
  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Blackbox exporter for external monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://admin.amysoft.tech
        - https://www.amysoft.tech
        - https://api.amysoft.tech
        - https://app.amysoft.tech
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL certificate monitoring
  - job_name: 'ssl-expiry'
    metrics_path: /probe
    params:
      module: [ssl_expiry]
    static_configs:
      - targets:
        - admin.amysoft.tech:443
        - www.amysoft.tech:443
        - api.amysoft.tech:443
        - app.amysoft.tech:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Global alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093