name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Update Nx workspace
      run: npx nx migrate latest

    - name: Install updated dependencies
      run: npm install

    - name: Run migrations
      run: npx nx migrate --run-migrations

    - name: Run tests to ensure compatibility
      run: npx nx run-many --target=test --all

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies and Nx workspace'
        title: 'Automated Dependency Updates'
        body: |
          This PR contains automated dependency updates including:
          - Nx workspace migration
          - Package dependency updates
          - Migration scripts execution
          
          All tests have been run to ensure compatibility.
        branch: chore/dependency-updates
        delete-branch: true

  security-updates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Fix security vulnerabilities
      run: npm audit fix --force

    - name: Create security update PR
      uses: peter-evans/create-pull-request@v5
      if: steps.audit.outputs.changed == 'true'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'security: fix vulnerabilities'
        title: 'Security: Fix Vulnerabilities'
        body: |
          This PR fixes security vulnerabilities found by npm audit.
          
          Please review the changes and ensure all functionality works correctly.
        branch: security/vulnerability-fixes
        delete-branch: true